/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ChessGameServer_CONSTANTS_H
#define ChessGameServer_CONSTANTS_H

#include "ChessGameServer_types.h"



class ChessGameServerConstants {
 public:
  ChessGameServerConstants();

};

extern const ChessGameServerConstants g_ChessGameServer_constants;



#endif
